### ISSUE TITLE
Update ClassGroupsController and fix pending spec

### ISSUE THREAD

**Issue by lolptdr** [makersquare/clicker#109]

**Comment by cath-oneill** [comment]
Not sure if this still needs to be done.  I think it was all taken care of in my pull request 100.  There is no longer a pending test.

**Comment by gilbert** [comment]
@lolptdr Can you confirm and close if that's the case?

**Comment by lolptdr** [comment]
@mindeavor Yup, Catherine's pull request #100 closes #109. Thanks, @cath-oneill!
