### ISSUE TITLE
Discuss Student Flow

### ISSUE THREAD

**Issue by gilbert** [makersquare/clicker#14]
![student_user_flow](https://cloud.githubusercontent.com/assets/5208932/4205258/c819a8aa-383e-11e4-9e4b-9bcd490de11d.png)

**Comment by RandyDavis** [comment]
![student_user_flow_updated](https://cloud.githubusercontent.com/assets/7109475/4208094/007a290e-385d-11e4-96f4-507d2dbc27ed.png)
