### ISSUE TITLE
Node.js SSE: Handle sessions.

### ISSUE THREAD

**Issue by gilbert** [makersquare/clicker#146]
Send the user's github username as the first message so you know it's working

**Comment by brianpatterson** [comment]
Add it so that there is an array of sessions which includes everyone who is currently logged into clicker.

**Comment by brianpatterson** [comment]
Created a fake gmail and github account with the usernames both clickclack app for testing purposes. Password for email is clickclackmakersquare and password for github is clickclackmakersquare8
