### ISSUE TITLE
Create Storyboards

### ISSUE THREAD

**Issue by gilbert** [makersquare/clicker#3]
@allizad @RandyDavis

Discuss and create storyboards based on the user stories. Post what you come up on this thread.

**Comment by allizad** [comment]
Teacher User flow edited and finished

**Comment by gilbert** [comment]
Great, can you upload the images here?

**Comment by allizad** [comment]
![student_user_flow](https://cloud.githubusercontent.com/assets/5208932/4205258/c819a8aa-383e-11e4-9e4b-9bcd490de11d.png)
![teacher_user_flow](https://cloud.githubusercontent.com/assets/5208932/4205259/c8211d24-383e-11e4-8e32-aa645bc8bfb4.png)

**Comment by gilbert** [comment]
Thanks! Since this is done early, we can discuss the student flow after lunch.
