### ISSUE TITLE
Create home controller and empty landing page

### ISSUE THREAD

**Issue by gilbert** [makersquare/clicker#36]

**Comment by lolptdr** [comment]
Waiting on "Add Foundation" issue resolve due to Home/Welcome controller created in that pull request... Will progress on other issues for now.

**Comment by allizad** [comment]
What error are you getting on that? it should resolve and work.

**Comment by lolptdr** [comment]
since you created the welcome/home controller, i didn't want to create another version and just encounter more conflicts, thanks for merging/pushing it! Starting it now...
