### ISSUE TITLE
Missing - Need to create description for our class groups

### ISSUE THREAD

**Issue by RandyDavis** [makersquare/clicker#46]
We need to have a description attached to each class group when they get created.  For example, the course name "Ruby Course" should have a description that we can show such as "A quick intro to Ruby".

**Comment by cath-oneill** [comment]
This is already done.

**Comment by RandyDavis** [comment]
We added the seed data for the class group "description" to use with the existing seed data.  OR you can make a new class and enter a description there to avoid the old error we were getting.  Closed!
